### ISSUE TITLE
Separate outputs

### ISSUE THREAD

**Issue by acturtle** [acturtle/cashflower#119]
We create a separate file for each modelpoint.

Do we need that? Can't it be one common output?

**Comment by zchmielewska** [comment]
It's okay if the run is aggregated because then we have always the same number of  row (e.g. 720 periods).

But for individual, it's not possible because for some variables there might be multiple records. 

For example, only one record for bel but 3 records for fund development because policyholder has 3 funds.

Then we have a mismatch in number of rows.

We can create common output for aggregated setting but I see it as a feature which is not extremly important.
