### ISSUE TITLE
Add flake8 setup.cfg

### ISSUE THREAD

**Issue by acturtle** [acturtle/cashflower#305]

**Comment by zchmielewska** [comment]
'+ write docs section about testing

**Comment by zchmielewska** [comment]
I have switched from flake8 to ruff because ruff can be configured in pyproject.toml.

It would be nice to have only pyproject.toml instead of multiple config files for different tools so that's the step into this direction.

The way this tool works seems to be basically the same as flake8 so for the developers this shouldn't matter.

The implemenation was done in: 283de2e6ee6de0dbbc7c79b5233d5acf23058264
